# Generated by Django 3.0.8 on 2020-09-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_testcases_case_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='case_name_en',
        ),
    ]
